### ISSUE TITLE
CountMatchingDefinitionDetails

### ISSUE THREAD

**Issue by Debbinson** [AndyButland/UmbracoPersonalisationGroupsCore#19]
``Hello @AndyButland ,
I also wanted to know if it's possible to replicate in some ways the old CountMatchingDefinitionDetails method. Which is contained in PersonalisationGroupMatcher for the library Zone.UmbracoPersonalisationGroups.
I have this code that I need to migrate in Umbraco 13: 
`var definition = group.Definition;
 var matchCount = PersonalisationGroupMatcher.CountMatchingDefinitionDetails(definition);`
Thank you in advance.

**Comment by AndyButland** [comment]
You can find the code for that in the [old repository here](https://github.com/AndyButland/UmbracoPersonalisationGroups/blob/7a0a19c910e1b2ddd7771233ea5ad946d02b16e9/Zone.UmbracoPersonalisationGroups.Common/PersonalisationGroupMatcher.cs#L45).

It's been a while since I did the migration to the new repo and Umbraco 9/.NET Core, so can't recall if this was removed deliberately or it was just an inadvertent omission.  I'll try to look at some point to see if it makes sense to add.

Meantime you can likely copy the implementation of that method into your own solution, or if, if were minded I'd happily accept a PR and then release an update to the current version of the package.

**Comment by AndyButland** [comment]
If you try version 3.3.0, you should find this method available now via the `IGroupMatchingService` interface.

I had actually migrated it to the implementation of this interface, but make the method private.  I've amended that to make it available on the interface.
